<%@ Page Title="" Language="C#" MasterPageFile="~/Site/MantTemplate.Master" AutoEventWireup="true" CodeBehind="ListaAlbum.aspx.cs" Inherits="WebFormTest.Site.AlbumWeb.ListaAlbum" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ButtonContent" runat="server">
    <a class="btn btn-primary" href="CrearAlbum.aspx">
        <span class="glyphicon glyphicon-plus"></span>Crear Álbum
    </a>
    <br />
    <div>
        Buscar Albúm
        <asp:TextBox ID="txtBuscar_Titulo" runat="server"></asp:TextBox>
        <asp:Button ID="btnBuscar" runat="server" Text="Buscar" OnClick="btnBuscar_Click" />
    </div>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ArtistContent" runat="server">
    <div class="row">
        <h3>Listado de Álbumes</h3>
    </div>
    <div>
        <br />
        <asp:GridView ID="AlbumGridView" runat="server"
            CssClass="table table-striped table-bordered"
            AllowPaging="true" 
            AllowSorting="true" 
            AutoGenerateColumns="true" 
            AutoGenerateDeleteButton="true" 
            AutoGenerateEditButton="true"
            DataKeyNames="AlbumId"
            PageSize="15"
            OnPageIndexChanging="AlbumGridView_PageIndexChanging"
        >
            <PagerSettings Mode="NumericFirstLast" Position="TopAndBottom" />
        </asp:GridView>
        <br />
        <asp:Button ID="btnFirst" runat="server" Text="Primer registro" OnClick="btnFirst_Click" />
        <asp:Button ID="btnLast" runat="server" Text="Último registro" OnClick="btnLast_Click" />
    </div>
</asp:Content>
