<%@ Page Title="" Language="C#" MasterPageFile="~/Site/MantTemplate.master" AutoEventWireup="true" CodeBehind="wfListado.aspx.cs" Inherits="WebForms.Site.PlaylistWeb.wfListado" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ButtonContent" runat="server">
    <br />
    <div>
        Playlist
        <asp:DropDownList ID="ddlPlaylist" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ddlPlaylist_SelectedIndexChanged"></asp:DropDownList>
        <asp:Button ID="btnPlaylistEditar" runat="server" Text="Editar" OnClick="btnPlaylistEditar_Click" />
    </div>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ArtistContent" runat="server">
    <div>
        <div class="row">
            <h3>Listado de Tracks por Playlist</h3>
        </div>
        <asp:GridView ID="gvPlaylist" runat="server"
            CssClass="table table-striped table-bordered"
            AllowPaging="true" 
            AllowSorting="true" 
            AutoGenerateColumns="true" 
            AutoGenerateDeleteButton="false" 
            AutoGenerateEditButton="false"
            DataKeyNames="PlaylistId,TrackId"
            PageSize="15"
            OnPageIndexChanging="gvPlaylist_PageIndexChanging"
        >
            <PagerSettings Mode="NumericFirstLast" Position="TopAndBottom" />
        </asp:GridView>
    </div>
</asp:Content>
